# Generated by Django 6.1.1 on 2026-09-17 15:10

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models

import api_auth.models.manager
import api_utils.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apicore", "0002_immutable_unaccent"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                (
                    "first_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
                (
                    "email_verified_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                ("is_staff", models.BooleanField(db_default=False, default=False)),
                ("is_superuser", models.BooleanField(db_default=False, default=False)),
            ],
            options={
                "ordering": ("username",),
                "abstract": False,
            },
            managers=[
                ("objects", api_auth.models.manager.ApiUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ApiUserGroups",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserGroupsEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserPermissions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserPermissionsEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserRecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserRecoveryCodeEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserTotpDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secret", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                (
                    "locked_until",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                ("failures", models.PositiveSmallIntegerField(db_default=0, default=0)),
                ("last_step", models.PositiveBigIntegerField(db_default=0, default=0)),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserTotpDeviceEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                (
                    "locked_until",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                ("failures", models.PositiveSmallIntegerField(db_default=0, default=0)),
                ("last_step", models.PositiveBigIntegerField(db_default=0, default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("purpose", models.CharField(max_length=30)),
                ("token_hash", models.CharField(max_length=128)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "consumed_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                (
                    "invalidated_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VerificationCodeEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("purpose", models.CharField(max_length=30)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "consumed_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                (
                    "invalidated_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                (
                    "first_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
                (
                    "email_verified_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                ("is_staff", models.BooleanField(db_default=False, default=False)),
                ("is_superuser", models.BooleanField(db_default=False, default=False)),
            ],
            options={
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        condition=models.Q(("pgh_context__isnull", False)),
                        fields=["pgh_context"],
                        name="gin_apiuserevent_ctx_path",
                        opclasses=["jsonb_path_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            expression=django.db.models.fields.json.KeyTextTransform(
                                "url", "pgh_context"
                            ),
                            name="gin_trgm_ops",
                        ),
                        condition=models.Q(("pgh_context__isnull", False)),
                        name="gin_apiuserevent_ctx_url",
                    ),
                    models.Index(
                        django.db.models.fields.json.KeyTransform(
                            "id",
                            django.db.models.fields.json.KeyTransform(
                                "user", "pgh_context"
                            ),
                        ),
                        condition=models.Q(
                            ("pgh_context__has_key", "user"),
                            ("pgh_context__isnull", False),
                        ),
                        name="idx_apiuserevent_ctx_userid",
                    ),
                    models.Index(
                        fields=["pgh_created_at"], name="idx_apiuserevent_pghcreatedat"
                    ),
                    models.Index(
                        fields=["pgh_label"], name="idx_apiuserevent_pghlabel"
                    ),
                    models.Index(fields=["id"], name="idx_apiuserevent_id"),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="644c006f1fe0ddb5cedec536a0ace636c9df8f2f",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_203fb",
                    table="apiauth_apiuserevent",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddField(
            model_name="apiusergroups",
            name="api_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiusergroups",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="groups",
            field=models.ManyToManyField(
                related_name="users", through="apiauth.ApiUserGroups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="apiusergroupsevent",
            name="api_user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiusergroupsevent",
            name="group",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissions",
            name="api_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissions",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="permissions",
            field=models.ManyToManyField(
                related_name="users",
                through="apiauth.ApiUserPermissions",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissionsevent",
            name="api_user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissionsevent",
            name="permission",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="apiusertotpdevice",
            name="api_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="totp_device",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiuserrecoverycodeevent",
            name="device",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiauth.apiusertotpdevice",
            ),
        ),
        migrations.AddField(
            model_name="apiuserrecoverycode",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="recovery_codes",
                to="apiauth.apiusertotpdevice",
            ),
        ),
        migrations.AddField(
            model_name="apiusertotpdeviceevent",
            name="api_user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="api_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="verification_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="verificationcodeevent",
            name="api_user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="apiusergroups",
            constraint=models.UniqueConstraint(
                fields=("api_user", "group"), name="unq_apiusergroups_apiuser_group"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="8d95991809115c54a7b519b7e98aa7febdbe92e3",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_7ef7a",
                    table="apiauth_apiusergroups",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="fa7af5056682135b7ddbd51e16b38fa53a862534",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_7c925",
                    table="apiauth_apiusergroups",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiusergroupsevent" ("api_user_id", "group_id", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."api_user_id", OLD."group_id", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="4e6eb9224e427b0042cd35d9b619e5b396df5dab",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_ce6ef",
                    table="apiauth_apiusergroups",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiusergroupsevent" ("api_user_id", "group_id", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."group_id", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="40fd94b294b4e71d98e7e3404d72c8f1e26a5aa4",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_40cf9",
                    table="apiauth_apiusergroups",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "apiauth_apiusergroupsevent" ("api_user_id", "group_id", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."group_id", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="39ee1e7b9e50a222d0dad7b16a0a8ea50164269b",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_4654e",
                    table="apiauth_apiusergroups",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiusergroupsevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiusergroupsevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiusergroupsevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_apiusergroupsevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiusergroupsevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(fields=["id"], name="idx_apiusergroupsevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroupsevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="5a4ebbe98b68a2a6fe23483e3e8c0aaadf1a9561",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_aac4c",
                    table="apiauth_apiusergroupsevent",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuserpermissions",
            constraint=models.UniqueConstraint(
                fields=("api_user", "permission"),
                name="unq_apiuserpermissions_apiuser_permission",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="8d1ea7a3588dc8ec266f7052eb99df2ed14f3ebd",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_7ce24",
                    table="apiauth_apiuserpermissions",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="d016fa06587165ad1b2c8ae0c40c8f82022d5f3c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_b42a6",
                    table="apiauth_apiuserpermissions",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserpermissionsevent" ("api_user_id", "id", "permission_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."api_user_id", OLD."id", OLD."permission_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="44733d851d5ec32a87f5badcb42e218f169996ab",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_007bc",
                    table="apiauth_apiuserpermissions",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserpermissionsevent" ("api_user_id", "id", "permission_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."id", NEW."permission_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="52c7be5219d87218dd3689a6ba77148ca8d7ca3a",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_62eb3",
                    table="apiauth_apiuserpermissions",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "apiauth_apiuserpermissionsevent" ("api_user_id", "id", "permission_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."id", NEW."permission_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="7fb4f4c82e61b6824f64c4af254d8047c7548fe0",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_30522",
                    table="apiauth_apiuserpermissions",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.functions.text.Upper(
                        api_utils.db.ImmutableUnaccent("username")
                    ),
                    name="gin_trgm_ops",
                ),
                name="gin_apiuser_username",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.functions.text.Upper(
                        api_utils.db.ImmutableUnaccent("email")
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("email__len__gt", 0)),
                name="gin_apiuser_email",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=models.Index(fields=["created_at"], name="idx_apiuser_createdat"),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=models.Index(
                fields=["email_verified_at"], name="idx_apiuser_emailverifiedat"
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=models.Index(fields=["is_active"], name="idx_apiuser_isactive"),
        ),
        migrations.AddConstraint(
            model_name="apiuser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("is_active", True)),
                name="unq_apiuser_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                condition=models.Q(("is_active", True)),
                name="unq_apiuser_username",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="2ae7cb711146e6862bbde182b6381641b6bfe595",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_60eb8",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="86d3d19ed637a35dc1f962d3c427fc101c73a76b",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_f50e9",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_touch_updatedat",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func="NEW.updated_at = NOW(); RETURN NEW;",
                    hash="11fe9982981d1ee538ec263ae9a909a17680de66",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_touch_updatedat_546b6",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_softdelete_isactive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='UPDATE "apiauth_apiuser" SET is_active = False WHERE "id" = OLD."id"; RETURN NULL;',
                    hash="76367b85f193d2a925492cc731ea917e80366b08",
                    operation="DELETE",
                    pgid="pgtrigger_trg_softdelete_isactive_0c036",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuser_protect_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot insert rows from % table', TG_TABLE_NAME;",
                    hash="bc386f0ec0fa89f0ebc42af45bae93b956745ff6",
                    operation="INSERT",
                    pgid="pgtrigger_trg_apiuser_protect_insert_79be2",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuser_unverify_email",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."email" IS DISTINCT FROM (NEW."email"))',
                    func="NEW.email_verified_at = NULL; RETURN NEW;",
                    hash="fb9a4c72535a4fdedb6bd8fd3640f65f4ee115ae",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiuser_unverify_email_75b56",
                    table="apiauth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserevent" ("created_at", "email", "email_verified_at", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "password", "pgh_context", "pgh_created_at", "pgh_label", "updated_at", "username") VALUES (OLD."created_at", OLD."email", OLD."email_verified_at", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_name", OLD."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."updated_at", OLD."username"); RETURN NULL;',
                    hash="b95c84438b93be25fbd2353d88be6a94127f35be",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_70bb8",
                    table="apiauth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserevent" ("created_at", "email", "email_verified_at", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "password", "pgh_context", "pgh_created_at", "pgh_label", "updated_at", "username") VALUES (NEW."created_at", NEW."email", NEW."email_verified_at", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", NEW."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."updated_at", NEW."username"); RETURN NULL;',
                    hash="94b79196a385885b0befa99324515be476590962",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_bf524",
                    table="apiauth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "apiauth_apiuserevent" ("created_at", "email", "email_verified_at", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "password", "pgh_context", "pgh_created_at", "pgh_label", "updated_at", "username") VALUES (NEW."created_at", NEW."email", NEW."email_verified_at", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", NEW."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."updated_at", NEW."username"); RETURN NULL;',
                    hash="f66193b5a022be012f4700267e04817258412d53",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_819c8",
                    table="apiauth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiuserpermissionsevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiuserpermissionsevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiuserpermissionsevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_apiuserpermissionsevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiuserpermissionsevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(fields=["id"], name="idx_apiuserpermissionsevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissionsevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="a74aee8363b6f282333a3fae5f243cde8e5f1ee1",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_e47c0",
                    table="apiauth_apiuserpermissionsevent",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdevice",
            index=models.Index(
                fields=["confirmed_at"], name="idx_apiusertotpdevice_confirmedat"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdevice",
            index=models.Index(
                fields=["locked_until"], name="idx_apiusertotpdevice_lockeduntil"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="992c84780255bb1335d646923595ed3a64c4b88f",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_e6814",
                    table="apiauth_apiusertotpdevice",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="ceb96653aba759cad52c5876053924bed26c2fc8",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_15d81",
                    table="apiauth_apiusertotpdevice",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiusertotpdevice_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."api_user_id" IS DISTINCT FROM (NEW."api_user_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="40dadc64a610ffd9a1ca091be6a314a75d0b1c62",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiusertotpdevice_readonly_7d6d2",
                    table="apiauth_apiusertotpdevice",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiusertotpdevice_protect_secret",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."confirmed_at" IS NOT NULL AND NEW."secret" IS DISTINCT FROM (OLD."secret"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="637c1c4957dc284340cc329c5bb6c30ae62552e7",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiusertotpdevice_protect_secret_dabaa",
                    table="apiauth_apiusertotpdevice",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiusertotpdevice_protect_confirmedat",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."confirmed_at" IS NOT NULL AND NEW."confirmed_at" IS NULL)',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="285936dc24f1624c78cb64c9ca0c575346a5adc5",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiusertotpdevice_protect_confirmedat_b78da",
                    table="apiauth_apiusertotpdevice",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiusertotpdeviceevent" ("api_user_id", "confirmed_at", "created_at", "failures", "id", "last_step", "locked_until", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."api_user_id", OLD."confirmed_at", OLD."created_at", OLD."failures", OLD."id", OLD."last_step", OLD."locked_until", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="98a5f726f4b1c064fbe2eb203af74896a4e9c50c",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_b057a",
                    table="apiauth_apiusertotpdevice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiusertotpdeviceevent" ("api_user_id", "confirmed_at", "created_at", "failures", "id", "last_step", "locked_until", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."confirmed_at", NEW."created_at", NEW."failures", NEW."id", NEW."last_step", NEW."locked_until", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="94aab84c828f8b9efdde8d314fedb8bf00bc657b",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_e5ab9",
                    table="apiauth_apiusertotpdevice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."api_user_id" IS DISTINCT FROM (NEW."api_user_id") OR OLD."confirmed_at" IS DISTINCT FROM (NEW."confirmed_at") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."failures" IS DISTINCT FROM (NEW."failures") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."last_step" IS DISTINCT FROM (NEW."last_step") OR OLD."locked_until" IS DISTINCT FROM (NEW."locked_until"))',
                    func='INSERT INTO "apiauth_apiusertotpdeviceevent" ("api_user_id", "confirmed_at", "created_at", "failures", "id", "last_step", "locked_until", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."confirmed_at", NEW."created_at", NEW."failures", NEW."id", NEW."last_step", NEW."locked_until", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="cd3a60be5aa7c29f555e66479aa7ab7ef4db4f0c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_670d2",
                    table="apiauth_apiusertotpdevice",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiuserrecoverycodeevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiuserrecoverycodeevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiuserrecoverycodeevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_apiuserrecoverycodeevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiuserrecoverycodeevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=models.Index(fields=["id"], name="idx_apiuserrecoverycodeevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycodeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="99891496740eee8790ee2c3ca03c89aeb38791dd",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_d727e",
                    table="apiauth_apiuserrecoverycodeevent",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycode",
            index=models.Index(
                fields=["used_at"], name="idx_apiuserrecoverycode_usedat"
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuserrecoverycode",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unq_apiuserrecoverycode_code"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="966a88fdb6ca44070401f6a365c22983157ec65a",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_6d55b",
                    table="apiauth_apiuserrecoverycode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="580e4c7294d667f39fd6029fba0bea07ea62094f",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_e50a9",
                    table="apiauth_apiuserrecoverycode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuserrecoverycode_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."device_id" IS DISTINCT FROM (NEW."device_id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="b80cd6498ff476e9cc236963dd30a9efdbba97d9",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiuserrecoverycode_readonly_54540",
                    table="apiauth_apiuserrecoverycode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuserrecoverycode_protect_used",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."used_at" IS NOT NULL)',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="d613750808a64babd5d695331532dfcde11209f8",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiuserrecoverycode_protect_used_f1cd7",
                    table="apiauth_apiuserrecoverycode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserrecoverycodeevent" ("created_at", "device_id", "id", "pgh_context", "pgh_created_at", "pgh_label", "used_at") VALUES (OLD."created_at", OLD."device_id", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."used_at"); RETURN NULL;',
                    hash="07db1ceae415a7596251e4ccbfe48551be062a72",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_c609b",
                    table="apiauth_apiuserrecoverycode",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserrecoverycodeevent" ("created_at", "device_id", "id", "pgh_context", "pgh_created_at", "pgh_label", "used_at") VALUES (NEW."created_at", NEW."device_id", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."used_at"); RETURN NULL;',
                    hash="768d884fd9f7edac4d811a2d9a21249abe27999a",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_82c50",
                    table="apiauth_apiuserrecoverycode",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."used_at" IS DISTINCT FROM (NEW."used_at"))',
                    func='INSERT INTO "apiauth_apiuserrecoverycodeevent" ("created_at", "device_id", "id", "pgh_context", "pgh_created_at", "pgh_label", "used_at") VALUES (NEW."created_at", NEW."device_id", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."used_at"); RETURN NULL;',
                    hash="f7090b36202b6c50fc34002c1eeaf44b89a18ea6",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_481c5",
                    table="apiauth_apiuserrecoverycode",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiusertotpdeviceevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiusertotpdeviceevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiusertotpdeviceevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_apiusertotpdeviceevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiusertotpdeviceevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=models.Index(fields=["id"], name="idx_apiusertotpdeviceevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdeviceevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="c79b5372ed73608170502d3372a5c4b7b828d344",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_4fa30",
                    table="apiauth_apiusertotpdeviceevent",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                condition=models.Q(
                    ("consumed_at__isnull", True), ("invalidated_at__isnull", True)
                ),
                fields=["expires_at"],
                name="idx_verificationcode_expiration",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcode",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose__in", ["email_verification"])),
                name="chk_verificationcode_purpose",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcode",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="chk_verificationcode_lifetime",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("consumed_at__isnull", True),
                    ("invalidated_at__isnull", True),
                    _connector="OR",
                ),
                name="chk_verificationcode_single_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcode",
            constraint=models.UniqueConstraint(
                fields=("token_hash",), name="unq_verificationcode_token"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcode",
            constraint=models.UniqueConstraint(
                models.F("purpose"),
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(
                    ("consumed_at__isnull", True), ("invalidated_at__isnull", True)
                ),
                name="unq_verificationcode_live",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationcode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="b43b62fcaaf88f02d2550a2e6ca0685ad9b5bfab",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_3d20b",
                    table="apiauth_verificationcode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationcode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="077af297558931c2d2a69877bbfd25ea9727a675",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_74243",
                    table="apiauth_verificationcode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationcode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_verificationcode_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."api_user_id" IS DISTINCT FROM (NEW."api_user_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."expires_at" IS DISTINCT FROM (NEW."expires_at") OR OLD."purpose" IS DISTINCT FROM (NEW."purpose") OR OLD."token_hash" IS DISTINCT FROM (NEW."token_hash"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="f191c168890ca9450dbd6ef19d11ac9ef71668aa",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_verificationcode_readonly_8db38",
                    table="apiauth_verificationcode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationcode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_verificationcode_protect_settled",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."consumed_at" IS NOT NULL OR OLD."invalidated_at" IS NOT NULL)',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="fa1d288bafe2977862619c58f4e1bf3534165a88",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_verificationcode_protect_settled_d07de",
                    table="apiauth_verificationcode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationcode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_verificationcodeevent" ("api_user_id", "consumed_at", "created_at", "email", "expires_at", "id", "invalidated_at", "pgh_context", "pgh_created_at", "pgh_label", "purpose") VALUES (OLD."api_user_id", OLD."consumed_at", OLD."created_at", OLD."email", OLD."expires_at", OLD."id", OLD."invalidated_at", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."purpose"); RETURN NULL;',
                    hash="c4d495fde643b916db8cd665380f777468cba88c",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_b9223",
                    table="apiauth_verificationcode",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationcode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_verificationcodeevent" ("api_user_id", "consumed_at", "created_at", "email", "expires_at", "id", "invalidated_at", "pgh_context", "pgh_created_at", "pgh_label", "purpose") VALUES (NEW."api_user_id", NEW."consumed_at", NEW."created_at", NEW."email", NEW."expires_at", NEW."id", NEW."invalidated_at", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."purpose"); RETURN NULL;',
                    hash="f4c1969cba0a93fa9d4dbca9642ae8817765df4a",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_f0b48",
                    table="apiauth_verificationcode",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationcode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."api_user_id" IS DISTINCT FROM (NEW."api_user_id") OR OLD."consumed_at" IS DISTINCT FROM (NEW."consumed_at") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."expires_at" IS DISTINCT FROM (NEW."expires_at") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."invalidated_at" IS DISTINCT FROM (NEW."invalidated_at") OR OLD."purpose" IS DISTINCT FROM (NEW."purpose"))',
                    func='INSERT INTO "apiauth_verificationcodeevent" ("api_user_id", "consumed_at", "created_at", "email", "expires_at", "id", "invalidated_at", "pgh_context", "pgh_created_at", "pgh_label", "purpose") VALUES (NEW."api_user_id", NEW."consumed_at", NEW."created_at", NEW."email", NEW."expires_at", NEW."id", NEW."invalidated_at", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."purpose"); RETURN NULL;',
                    hash="955a15995208884b9f2b7e261e559fd2d5f7dd35",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_82aab",
                    table="apiauth_verificationcode",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcodeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_verificationcodeevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcodeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_verificationcodeevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcodeevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_verificationcodeevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcodeevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_verificationcodeevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcodeevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_verificationcodeevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcodeevent",
            index=models.Index(fields=["id"], name="idx_verificationcodeevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationcodeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="b10b5f79a70d644df730cc74e32e3434d5d9229d",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_cd20d",
                    table="apiauth_verificationcodeevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
