[pytest]
  DJANGO_SETTINGS_MODULE = "api_core.settings"

  addopts = [
    "--cov",
    "--cov-report=term-missing",
    "--numprocesses=4",
    "--quiet",
    "--reuse-db",
  ]

  console_output_style = "count"
  pythonpath           = ["src"]
