[project]
  authors = [
    { name = "Joaquín Zúñiga", email = "jp.zuniga.dev@gmail.com" },
  ]

  dependencies = [
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "django-filter>=26.1",
    "django-health-check>=4.5.1",
    "django-modern-rest[jwt,msgspec,openapi,pydantic]>=0.15.0",
    "django-pgbulk>=3.3.0",
    "django-pghistory>=3.9.2",
    "django-pglock>=1.8.0",
    "django-pgtransaction>=2.1.0",
    "django-pgtrigger>=4.17.0",
    "granian>=2.8.3",
    "phonenumbers>=9.0.39",
    "psycopg[binary,pool]>=3.3.5",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "redis[hiredis]>=8.1.0",
  ]

  name            = "api"
  version         = "0.0.1"
  description     = "backend!"
  readme          = { file = "README.md" }
  requires-python = ">=3.14.0"
  license-files   = ["LICENSE.md"]

[dependency-groups]
  dev = [
    "faker>=40.39.0",
    "granian[reload]>=2.8.3",
    "hypothesis>=6.168.0",
    "polyfactory>=3.3.0",
    "prek>=0.5.3",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-django>=4.14.0",
    "rstr>=3.2.2",
    "ruff>=0.16.8",
    "schemathesis>=4.27.2",
    "tombi>=1.5.5",
    "tracecov>=0.24.2",
    "ty>=0.0.81",
    "typing-extensions>=4.16.0",
    "zensical>=0.0.62",
  ]
