# Generated by Django 6.1 on 2026-08-08 18:37

from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations

########################################################################################


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [TrigramExtension(), UnaccentExtension()]
