# Generated by Django 6.1 on 2026-08-08 23:50

from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from typing import Final

########################################################################################

FORWARD: Final[str] = """
CREATE OR REPLACE FUNCTION public.immutable_unaccent(text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
STRICT
AS $$ SELECT public.unaccent('public.unaccent'::regdictionary, $1) $$;
"""

REVERSE: Final[str] = "DROP FUNCTION IF EXISTS public.immutable_unaccent(text);"

########################################################################################


class Migration(migrations.Migration):
    dependencies = [("apicore", "0001_extensions")]

    operations = [migrations.RunSQL(reverse_sql=REVERSE, sql=FORWARD)]
